{% set name = "ispyb" %}
{% set version = "6.0.2" %}
{% set sha256 = "c857287ddcfc0550b684a2d31f01409dedb5cd12090acbe06c1f3cbfee7cf891" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DiamondLightSource/{{ name }}-api/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - mysql-connector-python
    - tabulate

test:
  imports:
    - ispyb
    - ispyb.connector
    - ispyb.connector.mysqlsp
    - ispyb.connector.ws
    - ispyb.interface
    - ispyb.sp
    - ispyb.ws

about:
  home: https://github.com/DiamondLightSource/ispyb-api
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Python package to access ISPyB database
  description: |
    This package provides a python interface to ISPyB.
    It can access the ISPyB database directly or (in
    future versions) run on top of the official ISPyB
    webservices API.
  dev_url: https://github.com/DiamondLightSource/ispyb-api
